#!/usr/bin/env python3
"""Generate web_ui_gen.h from index.html for embedding in ESP32 firmware.

Usage: python generate_web_ui.py
Reads index.html, writes web_ui_gen.h with minified HTML as a PROGMEM string.
"""
import re
from pathlib import Path

def main():
    src = Path(__file__).parent / "index.html"
    dst = Path(__file__).parent / "web_ui_gen.h"

    html = src.read_text(encoding="utf-8")

    # Minify: collapse whitespace between tags
    html = re.sub(r"\s+", " ", html)
    html = html.strip()

    lines = ["// Auto-generated by generate_web_ui.py - do not edit manually"]
    lines.append("#ifndef WEB_UI_GEN_H")
    lines.append("#define WEB_UI_GEN_H")
    lines.append("")
    lines.append(f"// Generated from: {src.name}")
    lines.append(f"// Size: {len(html)} bytes (minified)")
    lines.append("")
    lines.append("static const char WEB_UI[] PROGMEM =")

    # Split into ~120-char chunks
    chunk = ""
    for ch in html:
        if ch == '"':
            chunk += '\\"'
        elif ch == '\\':
            chunk += '\\\\'
        elif ch == '\n':
            chunk += '\\n'
        else:
            chunk += ch
        if len(chunk) >= 120:
            lines.append(f'  "{chunk}"')
            chunk = ""
    if chunk:
        lines.append(f'  "{chunk}"')
    lines.append("  ;")
    lines.append("")
    lines.append("#endif // WEB_UI_GEN_H")
    lines.append("")

    dst.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"Generated {dst} ({len(html)} bytes minified, {len(lines)} lines)")

if __name__ == "__main__":
    main()
